FROM golang:1.22.2-alpine

ENV ROOT=/app

WORKDIR ${ROOT}

COPY . .

RUN go install github.com/cosmtrek/air@latest
RUN go mod download && go mod verify

RUN apk add --no-cache alpine-sdk \
    mysql-client \
    mysql-dev
